### PR TITLE
v2.000: GF mastering

### PR DESCRIPTION
**Pull request by m4rc1e**
Hey @juandelperal,

I've spent my morning mastering the files. Firstly, thank you very much for the cleanliness of this repo :-), It was almost spot on.

My Changes involve making sure the the family passes our internal QA tooling for Glyphs, https://github.com/googlefonts/gf-glyphs-scripts.

Unfortunately, The fonts can't generate with the latest version of Glyphs, Version 2.4.2 (1059). 

screen shot 2017-09-07 at 11 54 47

Could you merge my pr then fix the OT code?

Once you've done that, regenerate the fonts and I will pr them to google/fonts.

cc @davelab6 @thlinard

### CODE REVIEW

**Comment by juandelperal** [comment]
@m4rc1e 
We have a LICENSE.md (your ofl.txt) and CONTRIBUTORS.txt (similar to AUTHORS.txt)
in the master branch
https://github.com/huertatipografica/Alegreya

Do you think we still need your files?
Also, I will add you to CONTRIBUTORS.txt :)
Thanks!

**Comment by m4rc1e** [comment]
LICENSE.md can be dropped since we have OFL.txt.

AUTHORS.txt is a requirement. It is basically the original project author. CONTRIBUTORS.txt is just anyone who has touched the project :-)

**Comment by juandelperal** [comment]
OK, thanks!

**Comment by juandelperal** [comment]
Hi!
By deleting `NULL` it works fine. The error seems to be a Glyphs bug. I will post it in the forum and post updates here. Thanks

**Comment by juandelperal** [comment]
https://forum.glyphsapp.com/t/syntax-error-while-exporting/1450/10
Running the Preflight script I get: 
`- Glyph NULL: Should be called uni0000 (Unicode: 0000)..`
If I rename it the file exports properly
@m4rc1e If this is OK I can commit the changes
Thanks

**Comment by m4rc1e** [comment]
@juandelperal thank you for this investigation!

By all means rename NULL. Previously, glyphs allowed NULL. I guess this has been changed.

**Comment by davelab6** [comment]
Authors is copyright holders (which can be companies) and contributors is
humans and can include people whose contributions while important are too
small for copyright to adhere, such as Marc's little engineering fixes

**Pull request merged**
